###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    redis:
      image: redis:alpine
      container_name: lara-shop-redis

    mysql:
      image: mysql:8.0
      container_name: lara-shop-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=shop
        - MYSQL_USER=shop
        - MYSQL_PASSWORD=shop
      ports:
        - "1027:3306"

    elasticsearch:
      image: elasticsearch:6.5.4
      container_name: lara-shop-elasticsearch

    webserver:
      image: nginx:alpine
      container_name: lara-shop-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "1025:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: lara-shop-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini

